// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1rgV4GsvaQgnpWqqvya9H3p4al8zWy4',
    appId: '1:410863550136:web:6445d0b9e7467204d3fe4d',
    messagingSenderId: '410863550136',
    projectId: 'dagda-social-network',
    authDomain: 'dagda-social-network.firebaseapp.com',
    storageBucket: 'dagda-social-network.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCNHMFPCVYsE8_gRPfwrsGWCAKKrvNzY',
    appId: '1:410863550136:android:5e65036623c40f07d3fe4d',
    messagingSenderId: '410863550136',
    projectId: 'dagda-social-network',
    storageBucket: 'dagda-social-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7XMh6r2UbAW3QQcXRHT4LftjchXUZjC8',
    appId: '1:410863550136:ios:24839e8d5c7eefc1d3fe4d',
    messagingSenderId: '410863550136',
    projectId: 'dagda-social-network',
    storageBucket: 'dagda-social-network.appspot.com',
    iosClientId: '410863550136-o9jd739qfrivrqcordcinlngdvm364jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7XMh6r2UbAW3QQcXRHT4LftjchXUZjC8',
    appId: '1:410863550136:ios:24839e8d5c7eefc1d3fe4d',
    messagingSenderId: '410863550136',
    projectId: 'dagda-social-network',
    storageBucket: 'dagda-social-network.appspot.com',
    iosClientId: '410863550136-o9jd739qfrivrqcordcinlngdvm364jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );
}
