name: Flutter test
on:
  pull_request:
    branches: [ "main" ]
jobs:
 test:
    name: Flutter tests
    env:
      my_secret: ${{secrets.commit_token}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter gen-l10n --use-deferred-loading
      - run: flutter test
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
         script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Test succeeded! ✅',
          });          
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
         script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Test failed! ❌',
          });